services:
  - type: web
    name: portfolio
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FLASK_SECURITY_PASSWORD_SALT
        sync: false
      - key: USERNAME
        sync: false
      - key: PASSWORD
        sync: false

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio
    plan: free 